---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.image.containerRegistry}}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
              name: http
              protocol: TCP
          envFrom:
          - configMapRef:
              name: {{ .Values.appName }}-config-map
